### ISSUE TITLE
Design a Navbar for landing page

### ISSUE THREAD

**Issue by dhruvjain23** [skanarul8002/MCA_HUB#6]
I am eager to participate in this project by contributing through design the Navbar for Login Page, which has the element of login , register , dark mode toggle button .

Can you please assign me this issue under hacktoberfest and hacktoberfest-acceted label. @skanarul8002

**Comment by skanarul8002** [comment]
Hi @dhruvjain23 , Can you please share your approach to solving this? I would be happy to assign you then!

**Comment by dhruvjain23** [comment]
Sure! , Basically on the first landing page , there are already links available for Login, Registering for the user, but I think if the Navbar is available , it improves the UI of the page. 
From Navbar user can login , registering, login as a guest and dark mode button .
I will use React Js and Tailwind CSS for designing this. 

Truly , I am a beginner to the open source contribution and contributing such open source projects like this helps to learn and enhance web dev skills.
Please let me know , How can I clarify more to your question . @skanarul8002

**Comment by skanarul8002** [comment]
ok i will assign you @dhruvjain23

**Comment by skanarul8002** [comment]
please ⭐ Star the repository if you haven't already. @dhruvjain23
